### ISSUE TITLE
ISO(s) from the test suite don't satisfy the expected output

### ISSUE THREAD

**Issue by yzgyyang** [yzgyyang/diffoscope#2] opened 2017-07-24 18:20 UTC
Diffoscope test cases:
- test_iso9660_content
- test_iso9660_rockridge

failed on my both FreeBSD (with `cdrtools`) and Arch (with `cdrkit` - `genisoimage`). Is it true that in fact the expected outputs are wrong?

Here's the info from the `tests/data/test1.iso` and `tests/data/test2.iso`:
```
✗ isoinfo -l -i test1.iso
Setting input-charset to 'UTF-8' from locale.

Directory listing of /
dr-xr-xr-x   1    0    0       2048 Jun 24 2015 [     23 02] . 
dr-xr-xr-x   1    0    0       2048 Jun 24 2015 [     23 02] .. 
-r-xr-xr-x   1    0    0          0 Jun 24 2015 [     25 00] LINK.;1 
-r-xr-xr-x   1    0    0          0 Jun 24 2015 [     25 00] NULL.;1 
-r-xr-xr-x   1    0    0        446 Jun 24 2015 [     25 00] TEXT.;1 

✗ isoinfo -l -i test2.iso
Setting input-charset to 'UTF-8' from locale.

Directory listing of /
dr-xr-xr-x   1    0    0       2048 Jun 24 2015 [     23 02] . 
dr-xr-xr-x   1    0    0       2048 Jun 24 2015 [     23 02] .. 
-r-xr-xr-x   1    0    0          0 Jun 24 2015 [     25 00] LINK.;1 
-r-xr-xr-x   1    0    0          0 Jun 24 2015 [     25 00] NULL.;1 
-r-xr-xr-x   1    0    0        671 Jun 24 2015 [     25 00] TEXT.;1 
```
However, in the expected output:
```
✗ cat iso9660_content_expected_diff 
@@ -1,7 +1,7 @@
 
 Directory listing of /
 d---------   0    0    0            2048 Jun 24 2015 [     23 02]  . 
 d---------   0    0    0            2048 Jun 24 2015 [     23 02]  .. 
 ----------   0    0    0               0 Jun 24 2015 [     25 00]  LINK.;1 
 ----------   0    0    0               0 Jun 24 2015 [     25 00]  NULL.;1 
-----------   0    0    0             446 Jun 24 2015 [     25 00]  TEXT.;1 
+----------   0    0    0             671 Jun 24 2015 [     25 00]  TEXT.;1 
```
@mapreri @infinity0

**Comment by yzgyyang** [comment] 2017-07-24 18:21
Here's the output for the test cases (same from both machines):

```
=================================== FAILURES ===================================
365 _____________________________ test_iso9660_content _____________________________
366                                                                                 
367 differences = [<Difference isoinfo -l -i {} -- isoinfo -l -i {} []>, <Difference isoinfo -l -i {} -R -- isoinfo -l -i {} -R []>, <Difference text -- text []>, <Difference link -- li    nk []>]
368                                                                                 
369     @skip_unless_tools_exist('isoinfo')                                         
370     def test_iso9660_content(differences):                                      
371         expected_diff = get_data('iso9660_content_expected_diff')               
372 >       assert differences[0].unified_diff == expected_diff                     
373 E       AssertionError: assert '@@ -1,7 +1,7...0] TEXT.;1 \n' == '@@ -1,7 +1,7 ...]  TEXT.;1 \n'
374 E           @@ -1,7 +1,7 @@                                                     
375 E                                                                               
376 E            Directory listing of /                                             
377 E         -  dr-xr-xr-x   1    0    0       2048 Jun 24 2015 [     23 02] .     
378 E         ?   - -- -- ^^^^^^                                                    
379 E         +  d---------   0    0    0            2048 Jun 24 2015 [     23 02]  . 
380 E         ?      ^^^^^^         ++++++++++                                     +...
381 E                                                                               
382 E         ...Full output truncated (17 lines hidden), use '-vv' to show         
383                                                                                 
384 tests/comparators/test_iso9660.py:47: AssertionError                            
385 ____________________________ test_iso9660_rockridge ____________________________
386                                                                                 
387 differences = [<Difference isoinfo -l -i {} -- isoinfo -l -i {} []>, <Difference isoinfo -l -i {} -R -- isoinfo -l -i {} -R []>, <Difference text -- text []>, <Difference link -- li    nk []>]
388                                                                                 
389     @skip_unless_tools_exist('isoinfo')                                         
390     def test_iso9660_rockridge(differences):                                    
391         expected_diff = get_data('iso9660_rockridge_expected_diff')             
392 >       assert differences[1].unified_diff == expected_diff                     
393 E       AssertionError: assert '@@ -1,7 +1,7...5 00] text \n' == '@@ -1,7 +1,7 ... 00]  text \n'
394 E           @@ -1,7 +1,7 @@                                                     
395 E                                                                               
396 E            Directory listing of /                                             
397 E         -  drwxr-xr-x   2 1000 1000       2048 Jun 24 2015 [     23 02] .     
398 E         ?                    ^^^^^^                                           
399 E         +  drwxr-xr-x   2 1750 1750            2048 Jun 24 2015 [     23 02]  . 
400 E         ?                  ++ ++++ ^^^^^                                     +...
401 E                                                                               
402 E         ...Full output truncated (24 lines hidden), use '-vv' to show         
403                                                                                 
404 tests/comparators/test_iso9660.py:52: AssertionError                            
405 ============== 2 failed, 255 passed, 99 skipped in 265.18 seconds ==============
```

**Comment by mapreri** [comment] 2017-07-26 11:35
```
mattia@warren ..cible/diffoscope/diffoscope/tests/data (git)-[master] % isoinfo -l -i test1.iso

Directory listing of /
d---------   0    0    0            2048 Jun 24 2015 [     23 02]  . 
d---------   0    0    0            2048 Jun 24 2015 [     23 02]  .. 
----------   0    0    0               0 Jun 24 2015 [     25 00]  LINK.;1 
----------   0    0    0               0 Jun 24 2015 [     25 00]  NULL.;1 
----------   0    0    0             446 Jun 24 2015 [     25 00]  TEXT.;1 
mattia@warren ..cible/diffoscope/diffoscope/tests/data (git)-[master] % isoinfo -l -i test2.iso 

Directory listing of /
d---------   0    0    0            2048 Jun 24 2015 [     23 02]  . 
d---------   0    0    0            2048 Jun 24 2015 [     23 02]  .. 
----------   0    0    0               0 Jun 24 2015 [     25 00]  LINK.;1 
----------   0    0    0               0 Jun 24 2015 [     25 00]  NULL.;1 
----------   0    0    0             671 Jun 24 2015 [     25 00]  TEXT.;1 
mattia@warren ..cible/diffoscope/diffoscope/tests/data (git)-[master] % 
```

I think this is a case caused by the different tool used.  The `isoinfo` used in debian comes from genisoimage instead of cdrtools (ISTR something about forking, licenses and stuff, don't know the details).  possibly something is different, although I'm buffled by such difference.

That said, could you please report it in the Debian bug tracker where all diffoscope bugs are collected; I don't believe reporting this here is so useful, where ~nobody would see it.  See the README about how to report bugs.

**Comment by emaste** [comment] 2017-07-26 20:57
> I think this is a case caused by the different tool used.

Yes it looks that way, @yzgyyang and I just discussed this in person. Most FreeBSD ports depend on cdrtools, but we also have cdrkit in the ports collection. @yzgyyang is going to prepare a patch to have "golden output" files for isoinfo from cdrtools in addition to the existing cdrkit, and we can choose the appropriate one based on the output of isoinfo --version

**Comment by yzgyyang** [comment] 2017-07-26 21:01
Plus, the differences between two outputs are really on permissions of files/directories. It's not something I should fix now, but it would be interesting to look at what happened in these two tools and which one is (more) correct.

**Comment by emaste** [comment] 2017-07-26 21:48
As far as I can tell the cdrtools is "more correct" here than cdrkit, but I see different permissions altogether when actually mounting test1.iso on FreeBSD.

**Comment by yzgyyang** [comment] 2017-08-02 00:41
@mapreri This patch is to detect if the `isoinfo` executable is from `cdrtools` (`cdrkit` by default) and use test cases created specifically for both tools.
[diffoscope_cdrtools_patch.diff.txt](https://github.com/yzgyyang/diffoscope/files/1192299/diffoscope_cdrtools_patch.diff.txt)

Commit:
https://github.com/yzgyyang/diffoscope/commit/d4b2f9a045a48e2b793eabd2a37516f07db1f239
https://github.com/yzgyyang/diffoscope/commit/53d67df050135d3790bfb0444013c27602ef541f

**Comment by mapreri** [comment] 2017-08-02 13:22
committed, and slightly modified.
Thank you for your contribution!

That said, could you please bring future bugs to the advertised bug tracker, as described in the README?

**Comment by yzgyyang** [comment] 2017-08-02 19:48
@mapreri Thank you! And sorry for the confusion, this repo is just for my own tracking. I will definitely use the Debian bug tracker in the future. In the meantime, could you please check out https://github.com/yzgyyang/diffoscope/issues/3 ?

**Closed as completed** 2017-08-02 19:48 UTC
